---
# file: roles/spark/tasks/main.yml

- name: create spark directory
  file: path={{ item }} state=directory
  with_items: spark.location
  tags:
    - spark
    - slaves

- name: download Apache Spark
  get_url: url=http://apache.mirror.cdnetworks.com/spark/spark-{{ spark.version }}/spark-{{ spark.version }}-bin-cdh4.tgz  dest=/tmp/spark-{{ spark.version }}-bin-cdh4.tgz mode=0644
  tags:
    - spark
    - slaves

- name: extract Apache Spark
  unarchive: src=/tmp/spark-{{ spark.version }}-bin-cdh4.tgz dest=/tmp copy=no
  tags:
    - spark
    - slaves

- name: move Apache Spark to target location
  shell: cp -rf /tmp/spark-{{ spark.version }}-bin-cdh4/* {{ spark.location }}
  tags:
    - spark
    - slaves

- name: copy spark-env.sh
  template: src=spark-env.sh dest={{ spark.location }}/conf/spark-env.sh
  tags:
    - spark
    - slaves
